project_id = "zidvkxhtglxxcsxlqhag"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[functions.process-edital]
verify_jwt = false

[functions.suggest-project]
verify_jwt = false

[functions.generate-proposal-pdf]
verify_jwt = false
